<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Regres</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>3e99ac16-3d0c-45f4-a67e-eb284410ef8f</testSuiteGuid>
   <testCaseLink>
      <guid>6c501a4f-35c3-4b26-a970-1902ef77b46b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Create Profile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1a7e9341-5a66-44c6-8a04-33369c0b2925</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d8d1254-681e-4181-a7fd-c2bfc04a2357</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>24ce2ba2-9466-48c4-85c2-077350251079</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Get Profile</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7a9214af-6e0a-446a-8372-322944b4698b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
